
const categs = {};
categs['ingresos'] = [
  {
    "id": 1,
    "nombre": "Ingresos",
    "tipo": {data: [1]},
    "imagen": null,
    "estado": 1,
    "id_presupuesto": null,
    "id_app": null,
    "disponible": "CO,CR,SV",
    "label_paises": [{"CO": "Ingresos","CR": "Ingresos","SV": "Ingresoss"}],
    "balance": 0,
    "subcategorias":   [{
              "id": 7,
              "nombre": "Auxilios / Horas Extras",
              "tipo": {data: [1]},
              "imagen": "Auxilios Horas extras_off",
              "estado": 1,
              "id_categoria": 1,
              "id_presupuesto": null,
              "id_app": null,
              "disponible": "CO,CR,SV",
              "label_paises": [{"CO": "Auxilios / Horas extras","CR": "Horas extra","SV": "Horas extras"}],
              "balance": 0,
              "subcategorias": null
            },
            {
              "id": 8,
              "nombre": "Comisiones / Bonificaciones",
              "tipo": {data: [1]},
              "imagen": "Comisiones Bonificaciones_off",
              "estado": 1,
              "id_categoria": 1,
              "id_presupuesto": null,
              "id_app": null,
              "disponible": "CO,CR,SV",
              "label_paises": [{"CO": "Comisiones / Bonificaciones","CR": "Comisiones / Bonificaciones","SV": "Comisiones / Bonificaciones"}],
              "balance": 0,
              "subcategorias": null
            },
            {
              "id": 1,
              "nombre": "Honorarios",
              "tipo": {data: [1]},
              "imagen": "Honorarios_off",
              "estado": 1,
              "id_categoria": 1,
              "id_presupuesto": null,
              "id_app": null,
              "disponible": "CO,CR,SV",
              "label_paises": [{"CO": "Honorarios","CR": "Honorarios","SV": "Honorarios"}],
              "balance": 0,
              "subcategorias": null
            },
            {
              "id": 4,
              "nombre": "Ingresos arriendos",
              "tipo": {data: [1]},
              "imagen": "Ingresos arriendos_off",
              "estado": 1,
              "id_categoria": 1,
              "id_presupuesto": null,
              "id_app": null,
              "disponible": "CO,CR,SV",
              "label_paises": [{"CO": "Ingresos arriendos","CR": "Ingresos por alquileres","SV": "Ingresos por alquileres"}],
              "balance": 0,
              "subcategorias": null
            },
            {
              "id": 5,
              "nombre": "Ingresos inversiones",
              "tipo": {data: [1]},
              "imagen": "Ingresos inversiones_off",
              "estado": 1,
              "id_categoria": 1,
              "id_presupuesto": null,
              "id_app": null,
              "disponible": "CO,CR,SV",
              "label_paises": [{"CO": "Ingresos inversiones","CR": "Ingresos inversiones","SV": "Ingresos inversiones"}],
              "balance": 0,
              "subcategorias": null
            },
            {
              "id": 6,
              "nombre": "Ingresos mesada / mensualidad",
              "tipo": {data: [1]},
              "imagen": "Ingresos mesada Mensualidad_off",
              "estado": 1,
              "id_categoria": 1,
              "id_presupuesto": null,
              "id_app": null,
              "disponible": "CO,CR,SV",
              "label_paises": [{"CO": "Ingresos mesada / Mensualidad","CR": "Ingresos mesada / Mensualidad","SV": "Ingresos mesada / Mensualidad"}],
              "balance": 0,
              "subcategorias": null
            },
            {
              "id": 2,
              "nombre": "Pensión",
              "tipo": {data: [1]},
              "imagen": "Pension_off",
              "estado": 1,
              "id_categoria": 1,
              "id_presupuesto": null,
              "id_app": null,
              "disponible": "CO,CR,SV",
              "label_paises": [{"CO": "Pensión","CR": "Pensión","SV": "Pensión"}],
              "balance": 0,
              "subcategorias": null
            },
            {
              "id": 3,
              "nombre": "Salario (despues de descuentos)",
              "tipo": {data: [1]},
              "imagen": "Salario_off",
              "estado": 1,
              "id_categoria": 1,
              "id_presupuesto": null,
              "id_app": null,
              "disponible": "CO,CR,SV",
              "label_paises": [{"CO": "Salario (despues de descuentos)","CR": "Salario (despues de deducciones)","SV": "Salario (despues de deducciones)"}],
              "balance": 0,
              "subcategorias": null
            }]
  },
  // {
  //   "id": 17,
  //   "nombre": "Otros Ingresos",
  //   "tipo": {data: [1]},
  //   "imagen": null,
  //   "estado": 1,
  //   "id_presupuesto": null,
  //   "id_app": null,
  //   "disponible": "CO,CR,SV",
  //   "label_paises": [{"CO": "Otros Ingresos","CR": "Otros Ingresos","SV": "Otros Ingresoss"}],
  //   "balance": 0,
  //   "subcategorias": []
  // },

]

categs['gastos'] = [
  {
    "id": 6,
    "nombre": "Créditos",
    "tipo": {data: [0]},
    "imagen": "Creditos_off",
    "estado": 1,
    "id_presupuesto": null,
    "id_app": null,
    "disponible": "CO,CR,SV",
    "label_paises": [{"CO": "Créditos","CR": "Créditos","SV": "Créditos"}],
    "balance": 0,
    "subcategorias":  [{"id": 23,
              "nombre": 'Cuota tarjeta de crédito 1',
              "disponible": 'CO,CR,SV',
              "label_paises": [{"CO": "Cuota tarjeta de crédito 1","CR": "Cuota tarjeta de crédito 1","SV": "Cuota tarjeta de crédito 1"}],
              "imagen": 'Cuota tarjeta de crédito', 
              "tipo": {data: [1]}, 
              "estado": '1',
              "id_app":  null,
              "id_presupuesto":  null,
              "id_categoria":  6}, 
              {"id": 24,
              "nombre": 'Cuota tarjeta de crédito 2',
              "disponible": 'CO,CR,SV',
              "label_paises": [{"CO": "Cuota tarjeta de crédito 2","CR": "Cuota tarjeta de crédito 2","SV": "Cuota tarjeta de crédito 2"}],
              "imagen": 'Cuota tarjeta de crédito', 
              "tipo": {data: [1]}, 
              "estado": '1',
              "id_app":  null,
              "id_presupuesto":  null,
              "id_categoria":  6},  
              {"id": 25,
              "nombre": 'Cuota crédito vehículo',
              "disponible": 'CO,CR,SV',
              "label_paises": [{"CO": "Cuota crédito vehículo","CR": "Cuota crédito vehículo","SV": "Cuota crédito vehículo"}],
              "imagen": 'cuota_crédito_vehículo', 
              "tipo": {data: [1]}, 
              "estado": '1',
              "id_app":  null,
              "id_presupuesto":  null,
              "id_categoria":  6},  
              {"id": 26,
              "nombre": 'Cuota crédito hipotecario',
              "disponible": 'CO,CR,SV',
              "label_paises": [{"CO": "Cuota crédito hipotecario","CR": "Cuota crédito hipotecario","SV": "Cuota crédito hipotecario"}],
              "imagen": 'Cuota crédito hipotecario', 
              "tipo": {data: [1]}, 
              "estado": '1',
              "id_app":  null,
              "id_presupuesto":  null,
              "id_categoria":  6},  
              {"id": 27,
              "nombre": 'Cuota crédito consumo',
              "disponible": 'CO,CR,SV',
              "label_paises": [{"CO": "Cuota crédito consumo","CR": "Cuota crédito consumo","SV": "Cuota crédito personal"}],
              "imagen": 'Cuota crédito consumo', 
              "tipo": {data: [1]}, 
              "estado": '1',
              "id_app":  null,
              "id_presupuesto":  null,
              "id_categoria":  6}, 
              {"id": 114,
              "nombre": 'Otras deudas',
              "disponible": 'CO,CR,SV',
              "label_paises": [{"CO": "Otras deudas","CR": "Otras deudas","SV": "Otras deudas"}],
              "imagen": 'Otras deudas', 
              "tipo": '0', 
              "estado": '1',
              "id_app":  null,
              "id_presupuesto":  null,
              "id_categoria":  6}]
  },
  {
    "id": 4,
    "nombre": "Educación",
    "tipo": {data: [0]},
    "imagen": "Educacion_off",
    "estado": 1,
    "id_presupuesto": null,
    "id_app": null,
    "disponible": "CO,CR,SV",
    "label_paises": [{"CO": "Educación","CR": "Educación e hijos","SV": "Educación e hijos"}],
    "balance": 0,
    "subcategorias": [{"id": 50, 
          "nombre": 'Pensión colegios', 
          "disponible": 'CO,CR,SV', 
          "label_paises": [{"CO": "Pensión colegios","CR": "Mensualidad escolar","SV": "Colegiatura"}], 
          "imagen": 'Pensión colegio',
          "tipo": {data: [1]},
          "estado": '1',
          "id_app": null,
          "id_presupuesto": null,
          "id_categoria": 4},
          {"id": 51, 
          "nombre": 'Matrícula universidad', 
          "disponible": 'CO,CR,SV', 
          "label_paises": [{"CO": "Matrícula universidad","CR": "Matrícula universidad","SV": "Matrícula"}], 
          "imagen": 'Matrícula universidad',
          "tipo": {data: [1]},
          "estado": '1',
          "id_app": null,
          "id_presupuesto": null,
          "id_categoria": 4},
          {"id": 52, 
          "nombre": 'Materiales escolares', 
          "disponible": 'CO,CR,SV', 
          "label_paises": [{"CO": "Materiales escolares","CR": "Materiales escolares","SV": "Materiales escolares"}], 
          "imagen": 'Materiales escolares',
          "tipo": {data: [1]},
          "estado": '1',
          "id_app": null,
          "id_presupuesto": null,
          "id_categoria": 4},
          {"id": 53, 
          "nombre": 'Mesada / Mensualidad de los hijos', 
          "disponible": 'CO,CR,SV', 
          "label_paises": [{"CO": "Mesada / Mensualidad de los hijos","CR": "Mesada / Mensualidad de los hijos","SV": "Mesada / Mensualidad de los hijos"}], 
          "imagen": 'Mesada Mensualidad de los hijos',
          "tipo": {data: [1]},
          "estado": '1',
          "id_app": null,
          "id_presupuesto": null,
          "id_categoria": 4},
          {"id": 54, 
          "nombre": 'Clases extras', 
          "disponible": 'CO,CR,SV', 
          "label_paises": [{"CO": "Clases extras","CR": "Clases extra","SV": "Clases extras"}], 
          "imagen": 'Clases extras',
          "tipo": {data: [1]},
          "estado": '1',
          "id_app": null,
          "id_presupuesto": null,
          "id_categoria": 4}]
  },
  {
    "id": 5,
    "nombre": "Entretenimiento",
    "tipo": {data: [0]},
    "imagen": "Entretenimiento_off",
    "estado": 1,
    "id_presupuesto": null,
    "id_app": null,
    "disponible": "CO,CR,SV",
    "label_paises": [{"CO": "Entretenimiento","CR": "Entretenimiento","SV": "Entretenimiento"}],
    "balance": 0,
    "subcategorias": [{"id" :  61,
                      "nombre" : 'Restaurantes',
                      "disponible" : 'CO,CR,SV',
                      "label_paises" :  [{"CO": "Restaurantes","CR": "Restaurantes","SV": "Restaurantes"}],
                      "imagen" : 'Restaurantes',
                      "tipo" : {data: [1]},
                      "estado" : '1', 
                      "id_app" : null, 
                      "id_presupuesto" : null, 
                      "id_categoria" : 5},
                      {"id" :62,
                      "nombre" :'Regalos',
                      "disponible" :'CO,CR,SV',
                      "label_paises" : [{"CO": "Regalos","CR": "Regalos","SV": "Regalos"}],
                      "imagen" :'Regalos',
                      "tipo": {data :[1]},
                      "estado" :'1', 
                      "id_app" :null, 
                      "id_presupuesto" :null, 
                      "id_categoria" :5},
                      {"id" : 63,
                      "nombre" : 'Descanso y diversión',
                      "disponible" : 'CO,CR,SV',
                      "label_paises" :  [{"CO": "Descanso y diversión","CR": "Descanso y diversión","SV": "Descanso y diversión"}],
                      "imagen" : 'Descanso y diversión',
                      "tipo" : {data: [1]},
                      "estado" : '1', 
                      "id_app" : null, 
                      "id_presupuesto" : null, 
                      "id_categoria" : 5},
                      {"id" : 64,
                      "nombre" : 'Hobbies',
                      "disponible" : 'CO,CR,SV',
                      "label_paises" :  [{"CO": "Hobbies","CR": "Pasatiempos","SV": "Pasatiempos"}],
                      "imagen" : 'Hobbies',
                      "tipo" : {data: [1]},
                      "estado" : '1', 
                      "id_app" : null, 
                      "id_presupuesto" : null, 
                      "id_categoria" : 5},
                      { "id" :  65,
                      "nombre" : 'Libros / Revistas / Periódicos',
                      "disponible" : 'CO,CR,SV',
                      "label_paises" :  [{"CO": "Libros / Revistas / Periódicos","CR": "Libros / Revistas / Periódicos","SV": "Libros / Revistas / Periódicos"}],
                      "imagen" : 'Libros Revistas Periódicos',
                      "tipo" : {data: [1]},
                      "estado" : '1', 
                      "id_app" : null, 
                      "id_presupuesto" : null, 
                      "id_categoria" : 5},
                      { "id" : 66,
                      "nombre" :'Vacaciones',
                      "disponible" :'CO,CR,SV',
                      "label_paises" : [{"CO": "Vacaciones","CR": "Vacaciones","SV": "Vacaciones"}],
                      "imagen" :'Vacaciones',
                      "tipo" : {data:[1]},
                      "estado" :'1', 
                      "id_app" :null, 
                      "id_presupuesto" :null, 
                      "id_categoria" :5}]
  },
  {
    "id": 3,
    "nombre": "Mercado",
    "tipo": {data: [0]},
    "imagen": "Mercado_off",
    "estado": 1,
    "id_presupuesto": null,
    "id_app": null,
    "disponible": "CO,CR,SV",
    "label_paises": [{"CO": "Mercado","CR": "Supermercado","SV": "Supermercado"}],
    "balance": 0,
    "subcategorias": [{"id": 28,
                        "nombre": 'Alimentos',
                        "disponible": 'CO,CR,SV',
                        "label_paises": [{"CO": "Alimentos","CR": "Alimentos","SV": "Alimentos"}],
                        "imagen": 'Alimentos',
                        "tipo": {data: [1]},
                        "estado": '1',
                        "id_app": null,
                        "id_presupuesto": null,
                        "id_categoria": 3
                      },{
                        "id": 29,
                        "nombre": 'Aseo',
                        "disponible": 'CO,CR,SV',
                        "label_paises": [{"CO": "Aseo","CR": "Aseo","SV": "Aseo"}],
                        "imagen": 'Aseo',
                        "tipo": {data: [1]},
                        "estado": '1',
                        "id_app": null,
                        "id_presupuesto": null,
                        "id_categoria": 3}]
  },
  {
    "id": 13,
    "nombre": "Obra / Remodelación",
    "tipo": {data: [0]},
    "imagen": "Obra Remodelacion_off",
    "estado": 1,
    "id_presupuesto": null,
    "id_app": null,
    "disponible": "CO,CR,SV",
    "label_paises": [{"CO": "Obra / Remodelación","CR": "Obra / Remodelación","SV": "Obra / Remodelación"}],
    "balance": 0,
    "subcategorias": [
      {"id":"96","nombre":"Honorarios arquitecto \/ Diseño","disponible":"CO,CR,SV","label_paises":[{"CO": "Honorarios arquitecto \/ Diseño","CR": "Honorarios arquitecto \/ Diseño","SV": "Honorarios arquitecto \/ Diseño"}],"imagen":"Honorarios arquitecto Diseño","tipo":{data: [1]},"estado":"1","id_app":null,"id_presupuesto":null,"id_categoria":"13"},
      {"id":"97","nombre":"Mano de obra","disponible":"CO,CR,SV","label_paises":[{"CO": "Mano de obra","CR": "Mano de obra","SV": "Mano de obra"}],"imagen":"Mano de obra","tipo":{data: [1]},"estado":"1","id_app":null,"id_presupuesto":null,"id_categoria":"13"},
      {"id":"98","nombre":"Carpintería","disponible":"CO,CR,SV","label_paises":[{"CO": "Carpintería","CR": "Carpintería","SV": "Carpintería"}],"imagen":"Carpintería","tipo":{data: [1]},"estado":"1","id_app":null,"id_presupuesto":null,"id_categoria":"13"},
      {"id":"99","nombre":"Mobiliario y decoración","disponible":"CO,CR,SV","label_paises":[{"CO": "Mobiliarios y decoración","CR": "Mobiliarios y decoración","SV": "Mobiliarios y decoración"}],"imagen":"Mobiliario y decoración","tipo":{data: [1]},"estado":"1","id_app":null,"id_presupuesto":null,"id_categoria":"13"},
      {"id":"100","nombre":"Mampostería (muros)","disponible":"CO,CR,SV","label_paises":[{"CO": "Mamposteria (muros)","CR": "Mamposteria (muros)","SV": "Mamposteria (muros)"}],"imagen":"Mampostería (muros)","tipo":{data: [1]},"estado":"1","id_app":null,"id_presupuesto":null,"id_categoria":"13"},
      {"id":"101","nombre":"Pisos y enchapes","disponible":"CO,CR,SV","label_paises":[{"CO": "Pisos y enchapes","CR": "Pisos y enchapes","SV": "Pisos y enchapes"}],"imagen":"Pisos y enchapes","tipo":{data: [1]},"estado":"1","id_app":null,"id_presupuesto":null,"id_categoria":"13"},
      {"id":"102","nombre":"Pintura","disponible":"CO,CR,SV","label_paises":[{"CO": "Pintura","CR": "Pintura","SV": "Pintura"}],"imagen":"Pintura","tipo":{data: [1]},"estado":"1","id_app":null,"id_presupuesto":null,"id_categoria":"13"},
      {"id":"103","nombre":"Instalaciones hidraúlicas","disponible":"CO,CR,SV","label_paises":[{"CO": "Instalaciones hidráulicas","CR": "Instalaciones hidráulicas","SV": "Instalaciones hidráulicas"}],"imagen":"Instalaciones hidraúlicas","tipo":{data: [1]},"estado":"1","id_app":null,"id_presupuesto":null,"id_categoria":"13"},
      {"id":"104","nombre":"Instalaciones eléctricas","disponible":"CO,CR,SV","label_paises":[{"CO": "Instalaciones eléctricas ","CR": "Instalaciones eléctricas ","SV": "Instalaciones eléctricas "}],"imagen":"Instalaciones eléctricas","tipo":{data: [1]},"estado":"1","id_app":null,"id_presupuesto":null,"id_categoria":"13"},
      {"id":"105","nombre":"Techos y cielos rasos","disponible":"CO,CR","label_paises":[{"CO": "Techos y cielos rasos","CR": "Techos y cielos rasos","SV": "Techos y cielos rasos"}],"imagen":"Techos y cielos rasos","tipo":{data: [1]},"estado":"1","id_app":null,"id_presupuesto":null,"id_categoria":"13"},
      {"id":"106","nombre":"Licencias","disponible":"CO,CR,SV","label_paises":[{"CO": "Permisos","CR": "Licencias y permisos","SV": "Permisos"}],"imagen":"Licencias","tipo":{data: [1]},"estado":"1","id_app":null,"id_presupuesto":null,"id_categoria":"13"},
      {"id":"107","nombre":"Administración obra","disponible":"CO,CR,SV","label_paises":[{"CO": "Materiales","CR": "Materiales","SV": "Materiales"}],"imagen":"Administración obra","tipo":{data: [1]},"estado":"1","id_app":null,"id_presupuesto":null,"id_categoria":"13"},
      {"id":"108","nombre":"Imprevistos","disponible":"CO,CR,SV","label_paises":[{"CO": "Imprevisto","CR": "Imprevisto","SV": "Imprevisto"}],"imagen":"Imprevistos","tipo":{data: [1]},"estado":"1","id_app":null,"id_presupuesto":null,"id_categoria":"13"},
      {"id":"109","nombre":"Ventanería","disponible":"CO,CR,SV","label_paises":[{"CO": "Ventaneria","CR": "Ventaneria","SV": "Ventaneria"}],"imagen":"Ventanería","tipo":{data: [1]},"estado":"1","id_app":null,"id_presupuesto":null,"id_categoria":"13"},
      {"id":"110","nombre":"Mobiliario baño","disponible":"CO,CR,SV","label_paises":[{"CO": "Mobiliario baño","CR": "Mobiliario baño","SV": "Mobiliario baño"}],"imagen":"Mobiliario baño","tipo":{data: [1]},"estado":"1","id_app":null,"id_presupuesto":null,"id_categoria":"13"},
      {"id":"111","nombre":"Mobiliario cocina","disponible":"CO,CR,SV","label_paises":[{"CO": "Mobiliario cocina","CR": "Mobiliario cocina","SV": "Mobiliario cocina"}],"imagen":"Mobiliario cocina","tipo":{data: [1]},"estado":"1","id_app":null,"id_presupuesto":null,"id_categoria":"13"},
      {"id":"112","nombre":"Iluminación","disponible":"CO,CR,SV","label_paises":[{"CO": "Iluminación","CR": "Iluminación","SV": "Iluminación"}],"imagen":"Iluminación","tipo":{data: [1]},"estado":"1","id_app":null,"id_presupuesto":null,"id_categoria":"13"},
      {"id":"113","nombre":"Cortinas","disponible":"CO,CR,SV","label_paises":[{"CO": "Cortinas","CR": "Cortinas","SV": "Cortinas"}],"imagen":"Cortinas","tipo":{data: [1]},"estado":"1","id_app":null,"id_presupuesto":null,"id_categoria":"13"}
      ]
  },
  {
    "id": 14,
    "nombre": "Reuniones y eventos",
    "tipo": {data: [0]},
    "imagen": "Reuniones y eventos_off",
    "estado": 1,
    "id_presupuesto": null,
    "id_app": null,
    "disponible": "CO,CR,SV",
    "label_paises": [{"CO": "Reuniones y eventos","CR": "Reuniones y eventos","SV": "Reuniones y eventos"}],
    "balance": 0,
    "subcategorias": [
      {"id":"81","nombre":"Alimentos","disponible":"CO,CR,SV","label_paises":[{"CO": "Alimentos","CR": "Alimentos","SV": "Alimentos"}],"imagen":"Alimentos2","tipo":{data: [1]},"estado":"1","id_app":null,"id_presupuesto":null,"id_categoria":"14"},
      {"id":"82","nombre":"Bebidas","disponible":"CO,CR,SV","label_paises":[{"CO": "Bebidas","CR": "Bebidas","SV": "Bebidas"}],"imagen":"Bebidas","tipo":{data: [1]},"estado":"1","id_app":null,"id_presupuesto":null,"id_categoria":"14"},
      {"id":"83","nombre":"Locación \/ Lugar","disponible":"CO,CR,SV","label_paises":[{"CO": "Locación \/ Lugar","CR": "Locación \/ Lugar","SV": "Locación \/ Lugar"}],"imagen":"Locación Lugar","tipo":{data: [1]},"estado":"1","id_app":null,"id_presupuesto":null,"id_categoria":"14"},
      {"id":"84","nombre":"Montaje (mesas, sillas, carpas)","disponible":"CO,CR,SV","label_paises":[{"CO": "Montaje (mesas, sillas, toldos)","CR": "Montaje (mesas, sillas, toldos)","SV": "Montaje (mesas, sillas, toldos)"}],"imagen":"Montaje (mesas, sillas, carpas)","tipo":{data: [1]},"estado":"1","id_app":null,"id_presupuesto":null,"id_categoria":"14"},
      {"id":"85","nombre":"Menaje (vajilla, copas, cubiertos)","disponible":"CO,CR,SV","label_paises":[{"CO": "Menaje (vajilla, copas, cubiertos)","CR": "Menaje (vajilla, copas, cubiertos)","SV": "Cristalería (vajilla, copas, cubiertos)"}],"imagen":"Menaje (vajilla, copas, cubiertos)","tipo":{data: [1]},"estado":"1","id_app":null,"id_presupuesto":null,"id_categoria":"14"},
      {"id":"86","nombre":"Decoración \/ Flores","disponible":"CO,CR,SV","label_paises":[{"CO": "Decoración \/ Flores","CR": "Decoración \/ Flores","SV": "Decoración \/ Flores"}],"imagen":"Decoración Flores","tipo":{data: [1]},"estado":"1","id_app":null,"id_presupuesto":null,"id_categoria":"14"},
      {"id":"87","nombre":"Fotografía \/ Video","disponible":"CO,CR,SV","label_paises":[{"CO": "Fotografía \/ Video","CR": "Fotografía \/ Video","SV": "Fotografía \/ Video"}],"imagen":"Fotografía Video","tipo":{data: [1]},"estado":"1","id_app":null,"id_presupuesto":null,"id_categoria":"14"},
      {"id":"88","nombre":"Personal de servicio \/ Meseros","disponible":"CO,CR,SV","label_paises":[{"CO": "Personal de servicio \/ Meseros","CR": "Personal de servicio \/ Meseros","SV": "Personal de servicio \/ Meseros"}],"imagen":"Personal de servicio Meseros","tipo":{data: [1]},"estado":"1","id_app":null,"id_presupuesto":null,"id_categoria":"14"},
      {"id":"89","nombre":"Recordatorios","disponible":"CO,CR","label_paises":[{"CO": "Recordatorios","CR": "Recuerdos","SV": "Recordatorios"}],"imagen":"Recordatorios","tipo":{data: [1]},"estado":"1","id_app":null,"id_presupuesto":null,"id_categoria":"14"},
      {"id":"90","nombre":"Invitaciones","disponible":"CO,CR,SV","label_paises":[{"CO": "Invitaciones","CR": "Invitaciones","SV": "Invitaciones"}],"imagen":"Invitaciones","tipo":{data: [1]},"estado":"1","id_app":null,"id_presupuesto":null,"id_categoria":"14"},
      {"id":"91","nombre":"Sonido \/ Música","disponible":"CO,CR,SV","label_paises":[{"CO": "Sonido \/ Música","CR": "Sonido \/ Música","SV": "Sonido \/ Música"}],"imagen":"Sonido Música","tipo":{data: [1]},"estado":"1","id_app":null,"id_presupuesto":null,"id_categoria":"14"},
      {"id":"92","nombre":"Ropa y accesorios","disponible":"CO,CR,SV","label_paises":[{"CO": "Ropa y accesorios","CR": "Ropa y accesorios","SV": "Ropa y accesorios"}],"imagen":"Ropa y accesorios","tipo":{data: [1]},"estado":"1","id_app":null,"id_presupuesto":null,"id_categoria":"14"},
      {"id":"93","nombre":"Salón de belleza","disponible":"CO,CR,SV","label_paises":[{"CO": "Salón de belleza","CR": "Salón de belleza","SV": "Salón de belleza"}],"imagen":"Salón de belleza","tipo":{data: [1]},"estado":"1","id_app":null,"id_presupuesto":null,"id_categoria":"14"},
      {"id":"94","nombre":"Transporte","disponible":"CO,CR,SV","label_paises":[{"CO": "Transporte","CR": "Transporte","SV": "Transporte"}],"imagen":"Transporte","tipo":{data: [1]},"estado":"1","id_app":null,"id_presupuesto":null,"id_categoria":"14"},
      {"id":"95","nombre":"Entretenimiento \/ Recreación","disponible":"CO,CR,SV","label_paises":[{"CO": "Entretenimiento \/ Recreación","CR": "Entretenimiento \/ Recreación","SV": "Entretenimiento \/ Recreación"}],"imagen":"Entretenimiento Recreación","tipo":{data: [1]},"estado":"1","id_app":null,"id_presupuesto":null,"id_categoria":"14"}
      ]
  },
  {
    "id": 8,
    "nombre": "Salud",
    "tipo": {data: [0]},
    "imagen": "Salud_off",
    "estado": 1,
    "id_presupuesto": null,
    "id_app": null,
    "disponible": "CO,CR,SV",
    "label_paises": [{"CO": "Salud","CR": "Salud","SV": "Salud"}],
    "balance": 0,
    "subcategorias": [{"id" :  47,
        "nombre" :  'Gastos médicos',
        "disponible" :  'CO,CR,SV',
        "label_paises" :  [{"CO": "Gastos médicos","CR": "Gastos médicos","SV": "Gastos médicos"}],
        "imagen" :  'Gastos médicos', 
        "tipo" :  '1', 
        "estado" :  '1',
        "id_app" :  null,
        "id_presupuesto" :  null,
        "id_categoria" : 8},
        {"id" :  48,
        "nombre" :  'Medicinas',
        "disponible" :  'CO,CR,SV',
        "label_paises" :  [{"CO": "Medicinas","CR": "Medicinas","SV": "Medicinas"}],
        "imagen" :  'Medicinas', 
        "tipo" :  '1', 
        "estado" :  '1',
        "id_app" :  null,
        "id_presupuesto" :  null,
        "id_categoria" : 8},
        {"id" : 49,
        "nombre" : 'Terapias',
        "disponible" : 'CO,CR,SV',
        "label_paises" : [{"CO": "Terapias","CR": "Terapias","SV": "Terapias"}],
        "imagen" : 'Terapias', 
        "tipo" : '1', 
        "estado" : '1',
        "id_app" : null,
        "id_presupuesto" : null,
        "id_categoria" :8}]
  },
  {
    "id": 9,
    "nombre": "Seguridad Social",
    "tipo": {data: [0]},
    "imagen": "Seguridad social_off",
    "estado": 1,
    "id_presupuesto": null,
    "id_app": null,
    "disponible": "CO,CR,SV",
    "label_paises": [{"CO": "Seguridad Social","CR": "Seguridad social independiente","SV": "Seguro voluntario"}],
    "balance": 0,
    "subcategorias": [{"id": 42,
            "nombre": 'Aportes obligatorio salud',
            "disponible": 'CO,CR,SV',
            "label_paises": [{"CO": "Aportes obligatorio salud","CR": "Aportes obligatorio salud","SV": "Aportes obligatorio salud"}],
            "imagen": 'Aportes obligatorio salud', 
            "tipo": {data: [1]}, 
            "estado": '1',
            "id_app": null,
            "id_presupuesto": null,
            "id_categoria": 9},
            {"id": 43,
            "nombre": 'Aportes obligatorio pensión',
            "disponible": 'CO,CR,SV',
            "label_paises": [{"CO": "Aportes obligatorio pensión","CR": "Aportes obligatorio pensión","SV": "Aportes obligatorio pensión"}],
            "imagen": 'Aportes obligatorio pensión', 
            "tipo": {data: [1]}, 
            "estado": '1',
            "id_app": null,
            "id_presupuesto": null,
            "id_categoria": 9},
            {"id": 44,
            "nombre": 'Aportes voluntarios pensiones',
            "disponible": 'CO,CR,SV',
            "label_paises": [{"CO": "Aportes voluntarios pensiones","CR": "Aportes voluntarios pensiones","SV": "Aportes voluntarios pensiones"}],
            "imagen": 'Aportes voluntarios pensiones', 
            "tipo": {data: [1]}, 
            "estado": '1',
            "id_app": null,
            "id_presupuesto": null,
            "id_categoria": 9},
            {"id": 45,
            "nombre": 'Aporte a riesgos laborales (ARL)',
            "disponible": 'CO',
            "label_paises": [{"CO": "Aporte ARL","CR": "","SV": ""}],
            "imagen": 'Aporte a riesgos laborales (ARL)', 
            "tipo": {data: [1]}, 
            "estado": '1',
            "id_app": null,
            "id_presupuesto": null,
            "id_categoria": 9},
            {"id": 46,
            "nombre": 'Aporte caja de compensación',
            "disponible": 'CO',
            "label_paises": [{"CO": "Aporte caja de compensación","CR": "","SV": ""}],
            "imagen": 'Aporte caja de compensación', 
            "tipo": {data: [1]}, 
            "estado": '1',
            "id_app": null,
            "id_presupuesto": null,
            "id_categoria": 9}]
  },
  {
    "id": 10,
    "nombre": "Seguros",
    "tipo": {data: [0]},
    "imagen": "Seguros_off",
    "estado": 1,
    "id_presupuesto": null,
    "id_app": null,
    "disponible": "CO,CR,SV",
    "label_paises": [{"CO": "Seguros","CR": "Seguros","SV": "Seguros"}],
    "balance": 0,
    "subcategorias": [
      {"id":"37","nombre":"Cuota seguro salud","disponible":"CO,CR,SV","label_paises":[{"CO": "Cuota seguro salud","CR": "Cuota seguro salud","SV": "Cuota seguro salud"}],"imagen":"Cuota seguro salud","tipo":{data: [1]},"estado":"1","id_app":null,"id_presupuesto":null,"id_categoria":"10"},
      {"id":"38","nombre":"Cuota seguro vida","disponible":"CO,CR,SV","label_paises":[{"CO": "Cuota seguro vida","CR": "Cuota seguro vida","SV": "Cuota seguro vida"}],"imagen":"seguro_vida\r","tipo":{data: [1]},"estado":"1","id_app":null,"id_presupuesto":null,"id_categoria":"10"},
      {"id":"39","nombre":"SOAT","disponible":"CO","label_paises":[{"CO": "SOAT","CR": "","SV": ""}],"imagen":"SOAT","tipo":{data: [1]},"estado":"1","id_app":null,"id_presupuesto":null,"id_categoria":"10"},
      {"id":"40","nombre":"Cuota seguro vehículo","disponible":"CO,CR,SV","label_paises":[{"CO": "Cuota seguro vehículo","CR": "Cuota seguro vehículo","SV": "Cuota seguro vehículo"}],"imagen":"Cuota seguro vehículo","tipo":{data: [1]},"estado":"1","id_app":null,"id_presupuesto":null,"id_categoria":"10"},
      {"id":"41","nombre":"Cuota seguro hogar","disponible":"CO,CR,SV","label_paises":[{"CO": "Cuota seguro hogar","CR": "Cuota seguro hogar","SV": "Cuota seguro hogar"}],"imagen":"Cuota seguro hogar","tipo":{data: [1]},"estado":"1","id_app":null,"id_presupuesto":null,"id_categoria":"10"}
      ]
  },
  {
    "id": 12,
    "nombre": "Servicios personales / Familiares",
    "tipo": {data: [0]},
    "imagen": "Servicios personales Familiares_off",
    "estado": 1,
    "id_presupuesto": null,
    "id_app": null,
    "disponible": "CO,CR,SV",
    "label_paises": [{"CO": "Servicios personales / familiares","CR": "Servicios personales / familiares","SV": "Servicios personales / familiares"}],
    "balance": 0,
    "subcategorias": [
      {"id":"30","nombre":"Lavandería","disponible":"CO,CR,SV","label_paises":[{"CO": "Lavandería","CR": "Lavandería","SV": "Lavandería"}],"imagen":"Lavandería","tipo":{data: [1]},"estado":"1","id_app":null,"id_presupuesto":null,"id_categoria":"12"},
      {"id":"31","nombre":"Peluquería","disponible":"CO,CR,SV","label_paises":[{"CO": "Peluquería","CR": "Peluquería","SV": "Peluquería"}],"imagen":"Peluquería","tipo":{data: [1]},"estado":"1","id_app":null,"id_presupuesto":null,"id_categoria":"12"},
      {"id":"32","nombre":"Gimnasio","disponible":"CO,CR,SV","label_paises":[{"CO": "Gimnasio","CR": "Gimnasio","SV": "Gimnasio"}],"imagen":"Gimnasio","tipo":{data: [1]},"estado":"1","id_app":null,"id_presupuesto":null,"id_categoria":"12"},
      {"id":"33","nombre":"Vestuario \/ Calzado","disponible":"CO,CR,SV","label_paises":[{"CO": "Vestuario \/ Calzado","CR": "Vestuario \/ Calzado","SV": "Vestuario \/ Calzado"}],"imagen":"Vestuario Calzado","tipo":{data: [1]},"estado":"1","id_app":null,"id_presupuesto":null,"id_categoria":"12"},
      {"id":"34","nombre":"Mascota","disponible":"CO,CR,SV","label_paises":[{"CO": "Mascota","CR": "Mascota","SV": "Mascota"}],"imagen":"Mascota","tipo":{data: [1]},"estado":"1","id_app":null,"id_presupuesto":null,"id_categoria":"12"},
      {"id":"35","nombre":"Donaciones y ayudas","disponible":"CO,CR,SV","label_paises":[{"CO": "Donaciones y ayudas","CR": "Donaciones y ayudas","SV": "Donaciones y ayudas"}],"imagen":"Donaciones y ayudas","tipo":{data: [1]},"estado":"1","id_app":null,"id_presupuesto":null,"id_categoria":"12"},
      {"id":"36","nombre":"Cuotas club \/ Asociaciones","disponible":"CO,CR,SV","label_paises":[{"CO": "Cuotas club \/ Asociaciones","CR": "Cuotas asociaciones o clubes","SV": "Cuotas asociaciones o clubes"}],"imagen":"Cuotas club Asociaciones","tipo":{data: [1]},"estado":"1","id_app":null,"id_presupuesto":null,"id_categoria":"12"}
      ]
  },
  {
    "id": 11,
    "nombre": "Servicios públicos / Privados",
    "tipo": {data: [0]},
    "imagen": "Servicios publicos Privados_off",
    "estado": 1,
    "id_presupuesto": null,
    "id_app": null,
    "disponible": "CO,CR,SV",
    "label_paises": [{"CO": "Servicios públicos / Privados","CR": "Servicios públicos / Privados","SV": "Servicios públicos / Privados"}],
    "balance": 0,
    "subcategorias": [
      {"id":"14","nombre":"Agua \/ Aseo","disponible":"CO,CR,SV","label_paises":[{"CO": "Agua \/ Aseo","CR": "Agua","SV": "Agua"}],"imagen":"Agua Aseo","tipo":{data: [1]},"estado":"1","id_app":null,"id_presupuesto":null,"id_categoria":"11"},
      {"id":"15","nombre":"Energía eléctrica","disponible":"CO,CR,SV","label_paises":[{"CO": "Energía eléctrica","CR": "Energía eléctrica","SV": "Energía eléctrica"}],"imagen":"Energía eléctrica","tipo":{data: [1]},"estado":"1","id_app":null,"id_presupuesto":null,"id_categoria":"11"},
      {"id":"16","nombre":"Gas","disponible":"CO,CR,SV","label_paises":[{"CO": "Gas","CR": "Gas","SV": "Gas"}],"imagen":"Gas","tipo":{data: [1]},"estado":"1","id_app":null,"id_presupuesto":null,"id_categoria":"11"},
      {"id":"17","nombre":"Teléfono fijo","disponible":"CO,CR,SV","label_paises":[{"CO": "Teléfono fijo","CR": "Teléfono fijo","SV": "Teléfono fijo"}],"imagen":"Teléfono fijo","tipo":{data: [1]},"estado":"1","id_app":null,"id_presupuesto":null,"id_categoria":"11"},
      {"id":"18","nombre":"Televisión por cable","disponible":"CO,CR,SV","label_paises":[{"CO": "Televisión por cable","CR": "Televisión por cable","SV": "Televisión por cable"}],"imagen":"Televisión por cable","tipo":{data: [1]},"estado":"1","id_app":null,"id_presupuesto":null,"id_categoria":"11"},
      {"id":"19","nombre":"Internet","disponible":"CO,CR,SV","label_paises":[{"CO": "Internet","CR": "Internet","SV": "Internet"}],"imagen":"Internet","tipo":{data: [1]},"estado":"1","id_app":null,"id_presupuesto":null,"id_categoria":"11"},
      {"id":"20","nombre":"Celular","disponible":"CO,CR,SV","label_paises":[{"CO": "Celular","CR": "Celular","SV": "Celular"}],"imagen":"Celular","tipo":{data: [1]},"estado":"1","id_app":null,"id_presupuesto":null,"id_categoria":"11"},
      {"id":"21","nombre":"Salario servicio doméstico","disponible":"CO,CR,SV","label_paises":[{"CO": "Salario servicio doméstico","CR": "Salario servicio doméstico","SV": "Salario servicio doméstico"}],"imagen":"Salario servicio doméstico","tipo":{data: [1]},"estado":"1","id_app":null,"id_presupuesto":null,"id_categoria":"11"},
      {"id":"22","nombre":"Seguridad social servicio doméstico","disponible":"CO,CR,SV","label_paises":[{"CO": "Seguridad social servicio doméstico","CR": "Seguridad social servicio doméstico","SV": "Seguridad social servicio doméstico"}],"imagen":"Seguridad social servicio doméstico","tipo":{data: [1]},"estado":"1","id_app":null,"id_presupuesto":null,"id_categoria":"11"}
      ]
  },
  {
    "id": 7,
    "nombre": "Transporte",
    "tipo": {data: [0]},
    "imagen": "Transporte_off",
    "estado": 1,
    "id_presupuesto": null,
    "id_app": null,
    "disponible": "CO,CR,SV",
    "label_paises": [{"CO": "Transporte","CR": "Transporte","SV": "Transporte"}],
    "balance": 0,
    "subcategorias": [{"id":55,
            "nombre":'Transporte público',
            "disponible":'CO,CR,SV',
            "label_paises":[{"CO": "Transporte público","CR": "Transporte público","SV": "Transporte público"}],
            "imagen":'Transporte público',
            "tipo":{data:[1]},
            "estado":'1',
            "id_app":null,
            "id_presupuesto":null,
            "id_categoria":7} ,
            {"id":56,
            "nombre":'Gasolina',
            "disponible":'CO,CR,SV',
            "label_paises":[{"CO": "Gasolina","CR": "Gasolina","SV": "Gasolina"}],
            "imagen":'Gasolina',
            "tipo":{data:[1]},
            "estado":'1',
            "id_app":null,
            "id_presupuesto":null,
            "id_categoria":7} ,
            {"id": 57,
            "nombre": 'Mantenimiento vehículo',
            "disponible": 'CO,CR,SV',
            "label_paises": [{"CO": "Mantenimiento vehículo","CR": "Mantenimiento vehículo","SV": "Mantenimiento vehículo"}],
            "imagen": 'Mantenimiento vehículo',
            "tipo": {data: [1]},
            "estado": '1',
            "id_app": null,
            "id_presupuesto": null,
            "id_categoria": 7} ,
            {"id":58,
            "nombre":'Impuesto vehículo',
            "disponible":'CO,CR,SV',
            "label_paises":[{"CO": "Impuesto vehículo","CR": "Impuesto vehículo","SV": "Impuesto vehículo"}],
            "imagen":'Impuesto vehículo',
            "tipo":{data:[1]},
            "estado":'1',
            "id_app":null,
            "id_presupuesto":null,
            "id_categoria":7},
            {"id": 59,
            "nombre": 'Peajes',
            "disponible": 'CO,CR',
            "label_paises": [{"CO": "Peajes","CR": "Peajes","SV": ""}],
            "imagen": 'Peajes',
            "tipo": {data: [1]},
            "estado": '1',
            "id_app": null,
            "id_presupuesto": null,
            "id_categoria": 7} ,
            {"id": 60,
            "nombre": 'Parqueaderos',
            "disponible": 'CO,CR,SV',
            "label_paises": [{"CO": "Parqueaderos","CR": "Parqueo","SV": "Estacionamiento"}],
            "imagen": 'Parqueaderos',
            "tipo": {data: [1]},
            "estado": '1',
            "id_app": null,
            "id_presupuesto": null,
            "id_categoria": 7}]
  },
  {
    "id": 15,
    "nombre": "Viaje",
    "tipo": {data: [0]},
    "imagen": "Viaje_off",
    "estado": 1,
    "id_presupuesto": null,
    "id_app": null,
    "disponible": "CO,CR,SV",
    "label_paises": [{"CO": "Viaje","CR": "Viaje","SV": "Viaje"}],
    "balance": 0,
    "subcategorias": [
      {"id":"67","nombre":"Tiquetes","disponible":"CO,CR,SV","label_paises":[{"CO": "Tiquetes","CR": "Tiquetes","SV": "Tiquetes"}],"imagen":"Tiquetes","tipo":{data: [1]},"estado":"1","id_app":null,"id_presupuesto":null,"id_categoria":"15"},
      {"id":"68","nombre":"Alojamiento","disponible":"CO,CR,SV","label_paises":[{"CO": "Alojamiento","CR": "Alojamiento","SV": "Alojamiento"}],"imagen":"Alojamiento","tipo":{data: [1]},"estado":"1","id_app":null,"id_presupuesto":null,"id_categoria":"15"},
      {"id":"69","nombre":"Transporte","disponible":"CO,CR,SV","label_paises":[{"CO": "Transporte","CR": "Transporte","SV": "Transporte"}],"imagen":"Transporte2","tipo":{data: [1]},"estado":"1","id_app":null,"id_presupuesto":null,"id_categoria":"15"},
      {"id":"70","nombre":"Alimentación","disponible":"CO,CR,SV","label_paises":[{"CO": "Alimentación","CR": "Alimentación","SV": "Alimentación"}],"imagen":"Alimentación","tipo":{data: [1]},"estado":"1","id_app":null,"id_presupuesto":null,"id_categoria":"15"},
      {"id":"71","nombre":"Entradas turísticas","disponible":"CO,CR,SV","label_paises":[{"CO": "Entradas turísticas","CR": "Entradas turísticas","SV": "Entradas turísticas"}],"imagen":"Entradas turísticas","tipo":{data: [1]},"estado":"1","id_app":null,"id_presupuesto":null,"id_categoria":"15"},
      {"id":"72","nombre":"Compras","disponible":"CO,CR,SV","label_paises":[{"CO": "Compras","CR": "Compras","SV": "Compras"}],"imagen":"Compras","tipo":{data: [1]},"estado":"1","id_app":null,"id_presupuesto":null,"id_categoria":"15"},
      {"id":"73","nombre":"Entretenimiento","disponible":"CO,CR,SV","label_paises":[{"CO": "Entretenimiento","CR": "Entretenimiento","SV": "Entretenimiento"}],"imagen":"Entretenimiento","tipo":{data: [1]},"estado":"1","id_app":null,"id_presupuesto":null,"id_categoria":"15"},
      {"id":"74","nombre":"Teléfono \/ Internet","disponible":"CO,CR,SV","label_paises":[{"CO": "Teléfono \/ Internet","CR": "Teléfono \/ Internet","SV": "Teléfono \/ Internet"}],"imagen":"Teléfono Internet","tipo":{data: [1]},"estado":"1","id_app":null,"id_presupuesto":null,"id_categoria":"15"},
      {"id":"75","nombre":"Propinas","disponible":"CO,CR,SV","label_paises":[{"CO": "Propinas","CR": "Propinas","SV": "Propinas"}],"imagen":"Propinas","tipo":{data: [1]},"estado":"1","id_app":null,"id_presupuesto":null,"id_categoria":"15"},
      {"id":"76","nombre":"Imprevistos","disponible":"CO,CR,SV","label_paises":[{"CO": "Imprevistos","CR": "Imprevistos","SV": "Imprevistos"}],"imagen":"Imprevistos3","tipo":{data: [1]},"estado":"1","id_app":null,"id_presupuesto":null,"id_categoria":"15"},
      {"id":"77","nombre":"Impuestos","disponible":"CO,CR,SV","label_paises":[{"CO": "Impuestos","CR": "Impuestos","SV": "Impuestos"}],"imagen":"Impuestos","tipo":{data: [1]},"estado":"1","id_app":null,"id_presupuesto":null,"id_categoria":"15"},
      {"id":"78","nombre":"Seguros de viaje","disponible":"CO,CR,SV","label_paises":[{"CO": "Seguro de viaje","CR": "Seguro de viaje","SV": "Seguro de viaje"}],"imagen":"Seguros de viaje","tipo":{data: [1]},"estado":"1","id_app":null,"id_presupuesto":null,"id_categoria":"15"},
      {"id":"79","nombre":"Combustible","disponible":"CO,CR,SV","label_paises":[{"CO": "Combustible","CR": "Combustible","SV": "Combustible"}],"imagen":"Combustible","tipo":{data: [1]},"estado":"1","id_app":null,"id_presupuesto":null,"id_categoria":"15"},
      {"id":"80","nombre":"Peajes","disponible":"CO,CR,SV","label_paises":[{"CO": "Peajes","CR": "Peajes","SV": "Peajes"}],"imagen":"Peajes2","tipo":{data: [1]},"estado":"1","id_app":null,"id_presupuesto":null,"id_categoria":"15"}
      ]
  },
  {
    "id": 2,
    "nombre": "Vivienda",
    "tipo": {data: [0]},
    "imagen": "Vivienda_off",
    "estado": 1,
    "id_presupuesto": null,
    "id_app": null,
    "disponible": "CO,CR,SV",
    "label_paises": [{"CO": "Vivienda","CR": "Vivienda","SV": "Vivienda"}],
    "balance": 0,
    "subcategorias": [{"id": 10,
                        "nombre": 'Arriendo',
                        "disponible": 'CO,CR,SV',
                        "label_paises": [{"CO": "Arriendo","CR": "Alquiler","SV": "Alquiler"}],
                        "imagen": 'Arriendo', 
                        "tipo": {data: [1]}, 
                        "estado": '1',
                        "id_app": null,
                        "id_presupuesto": null,
                        "id_categoria": 2
                      },
                      {"id": 11,
                        "nombre": 'Cuota de administración',
                        "disponible": 'CO,CR,SV',
                        "label_paises": [{"CO": "Cuota de administración","CR": "Cuota de administración","SV": "Cuota de administración"}],
                        "imagen": 'Cuota de administración', 
                        "tipo": {data: [1]}, 
                        "estado": '1',
                        "id_app": null,
                        "id_presupuesto": null,
                        "id_categoria": 2
                      },
                      {"id": 12,
                        "nombre": 'Impuesto Predial',
                        "disponible": 'CO,CR',
                        "label_paises": [{"CO": "Impuesto predial","CR": "Impuesto territorial","SV": ""}],
                        "imagen":  'Impuesto Predial', 
                        "tipo":  '1', 
                        "estado":  '1',
                        "id_app":  null,
                        "id_presupuesto":  null,
                        "id_categoria":  2
                      },
                      {"id": 13,
                        "nombre": 'Reparaciones / Mantenimiento',
                        "disponible": 'CO,CR,SV',
                        "label_paises": [{"CO": "Reparaciones / Mantenimiento","CR": "Reparaciones / Mantenimiento","SV": "Reparaciones / Mantenimiento"}],
                        "imagen": 'Reparaciones Mantenimiento', 
                        "tipo": {data: [1]}, 
                        "estado": '1',
                        "id_app": null,
                        "id_presupuesto": null,
                        "id_categoria": 2
                      }]
  }                 
]

export default categs;


