export enum SeoTitles{
  'Ingrese_sus_datos_para_iniciar_sesión',
  'Registro',
  'Recordar_contraseña',
  'Inicio',
  'Listado_presupuestos',
  'Balance_presupuesto',
  'Tipo_de_ingreso_presupuesto',
  'Valor_de_ingreso_del_presupuesto',
  'Agregar_tipo_de_ingresos',
  'Tipo_de_gastos_presupuesto',
  'Valor_de_gastos_del_presupuesto',
  'Agregar_tipo_de_gastos',
  'Editar_tipo_de_gastos_agregado',
  'Estadísticas_resumen',
  'Estadisticas_gastos_por_categoría',
  'Estadísticas_movimientos',
  'Estadísticasc_comparar',
  'Alertas_de_presupuesto',
  'Consejos_financieros',
  'Consejos_financieros_-_Administración_del_dinero',
  'Consejos_financieros_-_El_ahorro',
  'Consejos_financieros_-_Tarjetas_de_crédito',
  'Consejos_financieros_-_Seguridad_y_tecnología',
  'Consejos_financieros_-_Impuestos_y_seguros',
  'Consejos_financieros_-_El_dinero_en_la_familia',
  'Consejos_financieros_-_Crédito',
  'Cosejos_financieros_-_Vivienda_y_vehículo',
  'Consejos_financieros_-_Economía_y_finanzas',
  '5_pasos_para_lograr_la_independencia_financiera',
  'Cómo_planear_las_vacaciones_a_última_hora',
  '¿Sabia_que_un_colombiano_que_reside_en_el_exterior_puede_invertir_en_Colombia?',
  'Ahorre_tiempo_y_plata_anticipando_sus_compras_de_navidad',
  'Para_decorar_su_casa_en_navidad,_no_necesita_acabar_con_su_bolsillo',
  'Recomendaciones_financieras_para_las_festividades_decembrinas',
  '¿Cómo_obtener_un_buen_historial_crediticio_en_las_centrales_de_riesgo?',
  'No_deje_que_la_prima_se_vaya',
  'Revise_su_situación_financiera_antes_de_terminar_2018',
  'Prepare_sus_finanzas_personales_y_familiares_para_el_nuevo_año',
  '¿Qué_debe_tener_en_cuenta_para_comenzar_el_nuevo_año?',
  'Mesada:_la_oportunidad_para_aprender_a_manejar_el_dinero',
  'Pase_del_ahorro_a_la_inversión',
  'Controle_su(s)_peso(s)_en_el_gimnasio',
  '¿Qué_debe_tener_en_cuenta_a_la_hora_de_invertir?',
  '¿Cómo_enfrentar_el_sobre-endeudamiento?',
  '¿Cómo_elegir_una_cantidad_financiera_para_solicitar_un_crédito?',
  'Cómo_aprovechar_los_beneficios_de_seguros_de_sus_tarjetas_de_crédito',
  'Cómo_aprovechar_los_beneficios_de_asistencias_de_sus_tarjetas_de_crédito',
  'Recomendaciones_para_el_buen_uso_de_la_Tarjeta_de_Crédito',
  'Acciones_en_el_hogar_que_le_ayudarán_a_controlar_sus_gastos',
  '5_libros_para_aprender_sobre_finanzas_personales',
  'La_regla_50_20_30',
  '5_recomendaciones_para_controlar_los_gastos_pequeños',
  'Conozca_más_sobre_inversiones_financieras',
  'Micrometas_como_puntos_de_control',
  'Ojo_con_los_pequeños_gastos',
  'Avances_en_seguridad_digital',
  'Tips_para_ahorrar_a_la_hora_de_hacer_compras',
  'Buenos_hábitos_de_las_personas_exitosas',
  'Los_gastos_que_descuadran_su_presupuesto',
  '¡Tome_ya_la_decisión_de_ahorrar!',
  'Ahorre_en_sus_servicios_de_telecomunicaciones',
  'Cómo_ahorrar_en_fechas_especiales',
  'Cómo_ahorrar_en_los_gastos_de_su_mascota',
  'La_importancia_del_ahorro_y_los_seguros_en_la_familia',
  '¿Sabe_cómo_funcionan_los_bolsillos_de_ahorro?',
  'La_cuenta_de_ahorro_para_Pensionados',
  '4_recomendaciones_para_controlar_pequeños_gastos',
  'Conozca_las_diferencias_entre_ahorrar_e_invertir',
  'La_importancia_de_enseñarle_a_ahorrar_a_los_niños',
  'En_el_mes_del_ahorro,_lo_invitamos_a_ser_una_ardilla',
  'Mitos_sobre_el_ahorro',
  'Novios,_amigos_y_ahorradores',
  'Cómo_funciona_el_crédito_en_las_tarjetas_de_crédito',
  '5_beneficios_de_las_tarjetas_de_crédito_virtuales',
  'La_banca_digital_es_para_usted',
  'Seguridad_en_la_banca_virtual',
  '¿Qué_es_la_disrupción_digital?',
  'Más_canales_para_realizar_sus_transacciones_bancarias',
  'Uso_seguro_de_los_canales_digitales',
  'Domiciliación:_el_pago_de_sus_servicios,_siempre_al_día',
  'Beneficios_de_la_banca_digital',
  '¿Cómo_hacer_pagos_a_través_de_PSE?',
  'Pague_los_servicios_públicos_sin_salir_de_casa',
  'Facturas_electrónicas:_ayude_al_planeta_y_pague_desde_su_casa',
  'El_tiempo_es_oro._!No_lo_desperdicie_pagando_facturas!',
  'Pagos_y_transferencias_a_través_de_dispositivos_móviles',
  'Mitos_sobre_la_banca_digital',
  'Un_código_QR_puede_arreglarle_el_día',
  '¿Conoce_cómo_funcionan_las_pólizas_exequiales?',
  'Asegure_la_educación_de_sus_hijos_y_viva_tranquilo',
  '¿Sabe_cómo_funciona_el_seguro_de_desempleo?',
  'Seguros_no_convencionales',
  'Prepárese_para_Declarar_Renta_en_el_2019',
  'Cómo_aprovechar_los_alimentos_orgánicos_y_cuidar_el_bolsillo',
  'Ideas_de_menú_navideño',
  '4_propósitos_financieros_para_este_nuevo_año',
  '¿Cómo_manejar_el_apoyo_económico_que_pueden_requerir_sus_familiares?',
  'Los_errores_más_comunes_a_la_hora_de_manejar_las_finanzas_en_pareja',
  '¿Cómo_construir_patrimonio_en_pareja?',
  'El_manejo_del_dinero_ante_la_muerte_de_un_ser_querido',
  '¿Cómo_administrar_mejor_el_dinero_en_pareja?',
  'Involucre_a_sus_hijos_en_las_finanzas',
  'Aproveche_los_beneficios_del_seguro_de_su_vehículo',
  'Beneficios_de_comprar_vivienda',
  '¿Pensando_en_remodelar?',
  'Viaje_feliz_en_su_vehículo',
  'Su_vivienda,_lo_más_importante',
  '¿Cómo_impactan_los_indicadores_económicos_sus_finanzas_personales?',
  '¿Qué_tanto_impacta_el_precio_del_dólar_las_finanzas_personales_de_los_colombianos?'}

const seoInfo = [['Acceso a su cuenta de usuario aquí | Haga Cuentas','Acceda con sus credenciales de usuario en Haga Cuentas y explore sus presupuestos personales a cumplir a futuro. Entre desde acá','presupuesto, presupuestos, haga cuentas, finanzas personas, finanzas familiares, mis finanzas personales, educación financiera, cómo manejar sus finanzas'],
['Registro de nueva cuenta de usuario | Haga Cuentas','Regístrese en el portal de Haga Cuentas para acceder a herramientas de manejos de presupuestos y controle sus ingresos y gastos. Conozca más aquí','presupuesto, presupuestos, educación financiera, control de ingresos y gastos'],
['Recuerde sus datos de acceso a su cuenta de usuario aquí | Haga Cuentas','Recuerde sus datos de acceso con sus credenciales de usuario en Haga Cuentas y explore sus presupuestos personales a cumplir a futuro. Entre desde acá','presupuesto, presupuestos, haga cuentas, finanzas personas, finanzas familiares, mis finanzas personales, educación financiera, cómo manejar sus finanzas'],
['Administre mejor sus finanzas personales | Haga Cuentas','Aprenda sobre finanzas personales y educación financiera para lograr alcanzar más fácil sus metas aquí en Haga Cuentas de Davivienda. Conozca más aquí','presupuesto, presupuestos, haga cuentas, finanzas personas, finanzas familiares, mis finanzas personales, educación financiera, cómo manejar sus finanzas'],
['Listado de su presupuesto aquí | Haga Cuentas','Encuentre el listado de sus presupuestos y explore sus presupuestos personales a cumplir a futuro. Entre desde acá','presupuesto, presupuestos, haga cuentas, finanzas personas, finanzas familiares, mis finanzas personales, educación financiera, cómo manejar sus finanzas'],
['Balance de sus prespuesctos aquí Ingresos menos gastos | Haga Cuentas','Encuentre el balance de sus presupuestos aquí Ingresos menos Gastos. Entre desde acá','presupuesto, presupuestos, haga cuentas, finanzas personas, finanzas familiares, mis finanzas personales, educación financiera, cómo manejar sus finanzas'],
['Seleccione el tipo de ingreso de su presupuesto aquí | Haga Cuentas','Registre sus tipos ingresos mensuales en el prespuesto creado en Haga Cuentas lleve el control de sus ingresos. Conozca más aquí','ingresos, presupuesto, presupuestos, haga cuentas, finanzas personas, finanzas familiares, mis finanzas personales, educación financiera, cómo manejar sus finanzas'],
['Seleccione el valor del ingreso de su presupuesto aquí | Haga Cuentas','Registre el valor de sus ingresos mensuales en el prespuesto creado en Haga Cuentas lleve el control de sus ingresos. Conozca más aquí','ingresos, presupuesto, presupuestos, haga cuentas, finanzas personas, finanzas familiares, mis finanzas personales, educación financiera, cómo manejar sus finanzas'],
['Agregue una categoría de ingreso adicional de acuerdo a su prespuesto aquí | Haga Cuentas','Agregue un tipo de ingresos mensuales en el prespuesto creado en Haga Cuentas lleve el control de sus ingresos. Conozca más aquí','ingresos, presupuesto, presupuestos, haga cuentas, finanzas personas, finanzas familiares, mis finanzas personales, educación financiera, cómo manejar sus finanzas'],
['Seleccione el tipo de gasto de su presupuesto aquí | Haga Cuentas','Registre sus gastos mensuales en el prespuesto creado en Haga Cuentas lleve el control de sus ingresos. Conozca más aquí','gastos, presupuesto, presupuestos, haga cuentas, finanzas personas, finanzas familiares, mis finanzas personales, educación financiera, cómo manejar sus finanzas'],
['Seleccione el valor del gasto de su presupuesto aquí | Haga Cuentas','Registre el valor de sus gastos mensuales en el prespuesto creado en Haga Cuentas lleve el control de sus ingresos. Conozca más aquí','gastos, presupuesto, presupuestos, haga cuentas, finanzas personas, finanzas familiares, mis finanzas personales, educación financiera, cómo manejar sus finanzas'],
['Agregue una categoría de gasto adicional de acuerdo a su prespuesto aquí | Haga Cuentas','Agregue un tipo de gasto mensuales en el prespuesto creado en Haga Cuentas lleve el control de sus ingresos. Conozca más aquí','gastos, presupuesto, presupuestos, haga cuentas, finanzas personas, finanzas familiares, mis finanzas personales, educación financiera, cómo manejar sus finanzas'],
['Edite el tipo de categoría de gasto adicional de acuerdo a su presupuesto aquí | Haga Cuentas','Edite el tipo de categoría de gasto adicional de acuerdo a su presupuesto. Entre desde acá','gastos, presupuesto, presupuestos, haga cuentas, finanzas personas, finanzas familiares, mis finanzas personales, educación financiera, cómo manejar sus finanzas'],
['Consulte el resumen de su persupuesto aquí | Haga Cuentas','Consulte el resumen de su persupuesto aquí. Entre desde acá.','presupuesto, presupuestos, haga cuentas, finanzas personas, finanzas familiares, mis finanzas personales, educación financiera, cómo manejar sus finanzas'],
['Consulte los gastos por categoría de su presupusesto| Haga Cuentas','Consulte los gastos por categoría de su presupusesto. Entre desde acá.','presupuesto, presupuestos, haga cuentas, finanzas personas, finanzas familiares, mis finanzas personales, educación financiera, cómo manejar sus finanzas'],
['Consulte los movimientos de su presupuesto| Haga Cuentas','Consulte los movimientos de su presupuesto. Entre desde acá.','presupuesto, presupuestos, haga cuentas, finanzas personas, finanzas familiares, mis finanzas personales, educación financiera, cómo manejar sus finanzas'],
['Compare el compartamiento de sus presupuesto durante los último 3 ó 6 meses| Haga Cuentas','Compare el compartamiento de sus presupuesto durante los último 3 ó 6 meses. Entre desde acá. ','presupuesto, presupuestos, haga cuentas, finanzas personas, finanzas familiares, mis finanzas personales, educación financiera, cómo manejar sus finanzas'],
['Cree alertas para sus presupuesto y realice seguimiento a sus ingresos y gastos | Haga Cuenta','Cree alertas para sus presupuesto y realice seguimiento a sus ingresos y gastos. Entre desde acá.','presupuesto, presupuestos, haga cuentas, finanzas personas, finanzas familiares, mis finanzas personales, educación financiera, cómo manejar sus finanzas'],
['Tips Consejos Financieros | Haga Cuentas','Encuentre tips financieros, recomendaciones y consejos sobre educación financiera y el manejo del dinero para lograr todas sus metas ¡Entre y aprenda ya!','tips consejo financieros'],
['Tips Consejos Financieros | Haga Cuentas','Encuentre tips financieros, recomendaciones y consejos sobre educación financiera y el manejo del dinero para lograr todas sus metas ¡Entre y aprenda ya!','tips consejo financieros'],
['Tips Consejos Financieros | Haga Cuentas','Encuentre tips financieros, recomendaciones y consejos sobre educación financiera y el manejo del dinero para lograr todas sus metas ¡Entre y aprenda ya!','tips consejo financieros'],
['Tips Consejos Financieros | Haga Cuentas','Encuentre tips financieros, recomendaciones y consejos sobre educación financiera y el manejo del dinero para lograr todas sus metas ¡Entre y aprenda ya!','tips consejo financieros'],
['Tips Consejos Financieros | Haga Cuentas','Encuentre tips financieros, recomendaciones y consejos sobre educación financiera y el manejo del dinero para lograr todas sus metas ¡Entre y aprenda ya!','tips consejo financieros'],
['Tips Consejos Financieros | Haga Cuentas','Encuentre tips financieros, recomendaciones y consejos sobre educación financiera y el manejo del dinero para lograr todas sus metas ¡Entre y aprenda ya!','tips consejo financieros'],
['Tips Consejos Financieros | Haga Cuentas','Encuentre tips financieros, recomendaciones y consejos sobre educación financiera y el manejo del dinero para lograr todas sus metas ¡Entre y aprenda ya!','tips consejo financieros'],
['Tips Consejos Financieros | Haga Cuentas','Encuentre tips financieros, recomendaciones y consejos sobre educación financiera y el manejo del dinero para lograr todas sus metas ¡Entre y aprenda ya!','tips consejo financieros'],
['Tips Consejos Financieros | Haga Cuentas','Encuentre tips financieros, recomendaciones y consejos sobre educación financiera y el manejo del dinero para lograr todas sus metas ¡Entre y aprenda ya!','tips consejo financieros'],
['Tips Consejos Financieros | Haga Cuentas','Encuentre tips financieros, recomendaciones y consejos sobre educación financiera y el manejo del dinero para lograr todas sus metas ¡Entre y aprenda ya!','tips consejo financieros'],
['Tips Consejos Financieros | Haga Cuentas','5 pasos para lograr la independencia financiera','tips consejo financieros'],
['Tips Consejos Financieros | Haga Cuentas','Cómo planear las vacaciones a última hora Planear vacaciones a última hora puede resultar más costoso; sin embargo, si no planeó y ahorró para sus vacaciones con tiempo','tips consejo financieros'],
['Tips Consejos Financieros | Haga Cuentas','Sabía que… un colombiano que reside en el exterior puede invertir en Colombia? Conozca cómo hacerlo y cuáles alternativas existen para empezar a construir un patrimonio.','tips consejo financieros'],
['Tips Consejos Financieros | Haga Cuentas','Ahorre tiempo y plata anticipando sus compras de navidad Se acerca la temporada decembrina y con ella las tradicionales compras navideñas.','tips consejo financieros'],
['Tips Consejos Financieros | Haga Cuentas','Para decorar su casa en navidad, no necesita acabar con su bolsillo Diciembre es un mes de gastos: hay que tener dinero para vacaciones, viajes, comida, reuniones, regalos, novenas y la tradicional decoración navideña.','tips consejo financieros'],
['Tips Consejos Financieros | Haga Cuentas','Recomendaciones financieras para las festividades decembrinas','tips consejo financieros'],
['Tips Consejos Financieros | Haga Cuentas','¿Cómo obtener un buen historial crediticio en las centrales de riesgo? Para ello es importante cumplir con las siguientes condiciones: Tener un excelente comportamiento financiero, estar al día en los pagos y manejar bien los créditos.','tips consejo financieros'],
['Tips Consejos Financieros | Haga Cuentas','No deje que la prima se vaya Se aproxima la prima de Navidad para los empleados y, con ella, la tentación de gastar, por lo tanto es una buena oportunidad para darle un uso responsable.','tips consejo financieros'],
['Tips Consejos Financieros | Haga Cuentas','Revise su situación financiera antes de terminar 2018 Al final del año es costumbre revisar lo que hemos hecho bien y lo que no tanto.','tips consejo financieros'],
['Tips Consejos Financieros | Haga Cuentas','Prepare sus finanzas personales y familiares para el nuevo año','tips consejo financieros'],
['Tips Consejos Financieros | Haga Cuentas','¿Qué debe tener en cuenta para comenzar el nuevo año? Luego de revisar sus metas y fijar sus propósitos para 2019, el paso a seguir es organizar sus finanzas.Dedíquele un día a sus finanzas personales, revise cómo cerró 2018 y qué cambios debe hacer','tips consejo financieros'],
['Tips Consejos Financieros | Haga Cuentas','Mesada: la oportunidad para aprender a manejar el dinero La mesada es el dinero que los padres entregan periódicamente a sus hijos para que cubran sus necesidades y gustos mientras son estudiantes.','tips consejo financieros'],
['Tips Consejos Financieros | Haga Cuentas','Pase del ahorro a la inversión Los buenos hábitos de ahorro e inversión impactan positivamente su vida y la de su familia; por ejemplo, le permiten estar preparado ante un evento inesperado, cumplir las metas en el largo plazo y estar listo para cuando llegue el momento del retiro o jubilación.','tips consejo financieros'],
['Tips Consejos Financieros | Haga Cuentas','Controle su(s) peso(s) en el gimnasio Muchos tenemos el propósito de bajar de peso; además es saludable y gratificante.','tips consejo financieros'],
['Tips Consejos Financieros | Haga Cuentas','¿Qué debe tener en cuenta a la hora de invertir? Invertir es fundamental para construir patrimonio; por eso es importante que tenga en cuenta lo siguiente: Antes de realizar una inversión, revise su flujo de efectivo para que no afecte sus necesidades inmediatas.','tips consejo financieros'],
['Tips Consejos Financieros | Haga Cuentas','¿Cómo enfrentar el sobre-endeudamiento? Si las deudas que tiene le generan angustia, siga estas recomendaciones','tips consejo financieros'],
['Tips Consejos Financieros | Haga Cuentas','¿Cómo elegir una entidad financiera para solicitar un crédito? Antes de elegir con cuál entidad tomar un crédito, busque la información necesaria y analícela. Revise también su presupuesto para identificar su capacidad de pago.','tips consejo financieros'],
['Tips Consejos Financieros | Haga Cuentas','Cómo aprovechar los beneficios de seguros de sus tarjetas de crédito Consulte con su entidad bancaria cuáles seguros le ofrecen sus tarjetas de crédito y confirme las condiciones y requisitos para usarlos, las coberturas a que tiene derecho y las restricciones y exclusiones.','tips consejo financieros'],
['Tips Consejos Financieros | Haga Cuentas','Cómo aprovechar los beneficios de asistencias de sus tarjetas de crédito Para obtener el mejor provecho de estos beneficios consulte con la entidad bancaria qué tipos de asistencias nacionales e internaciones le ofrecen, ya que pueden variar entre productos, qué debe hacer para acceder a estas y confirme las condiciones y requisitos para usarlas.','tips consejo financieros'],
['Tips Consejos Financieros | Haga Cuentas','Recomendaciones para el buen uso de la Tarjeta de Crédito Tenga un uso responsable y evite asumir deudas que sobrepasen su capacidad de pago.','tips consejo financieros'],
['Tips Consejos Financieros | Haga Cuentas','Considere el costo del arriendo, muchas veces las cuotas de arriendo son similares a las que pagaría si tuviera casa propia con crédito hipotecario o leasing habitacional, además de los beneficios tributarios que ofrecen estos productos.','tips consejo financieros'],
['Tips Consejos Financieros | Haga Cuentas','5 Libros para aprender sobre finanzas personales Padre rico padre pobre. Escrito por Robert Kiyosaki y Sharon Lechter, explica de manera anecdótica conceptosfinancieros y sostiene que la poca de educación es la base de los problemas económicos, pues las personas no se endeudan por falta de ingresos sino por malgastar el dinero que tienen o por no invertirlo bien.','tips consejo financieros'],
['Tips Consejos Financieros | Haga Cuentas','La regla 50 - 20 - 30 Dentro de las fórmulas para ahorrar y organizar las finanzas personales y familiares está la regla 50-20-30','tips consejo financieros'],
['Tips Consejos Financieros | Haga Cuentas','5 recomendaciones para controlar los gastos pequeños','tips consejo financieros'],
['Tips Consejos Financieros | Haga Cuentas','Conozca más sobre inversiones financieras Con las inversiones financieras se busca obtener un beneficio sobre un capital que se posee, ganando rendimientos en un determinado tiempo.','tips consejo financieros'],
['Tips Consejos Financieros | Haga Cuentas','Micrometas como puntos de control En la vida es importante tener metas y una buena forma de trazarlas es definiéndolas desde cinco características: que sean Medibles, Específicas, con un Tiempo establecido, Alcanzables y Significativas.','tips consejo financieros'],
['Tips Consejos Financieros | Haga Cuentas','Ojo con los pequeños gastos Un antiguo refrán habla de cuidar los centavos, pues los pesos se cuidan solos. Esto se aplica a las finanzas personales, ya que los pequeños gastos pueden consumir una buena porción de sus ingresos sin que se de cuenta.','tips consejo financieros'],
['Tips Consejos Financieros | Haga Cuentas','Avances en seguridad digital Los avances tecnológicos han permitido que los canales digitales de las entidades financieras incorporen herramientas que garantizan la seguridad del dinero y las transacciones de sus clientes, mitigando el riesgo de suplantaciones y fraude.','tips consejo financieros'],
['Tips Consejos Financieros | Haga Cuentas','Tips para ahorrar a la hora de hacer compras A todos nos ha pasado que salimos a hacer compras para el hogar y terminamos pagando más.','tips consejo financieros'],
['Tips Consejos Financieros | Haga Cuentas','Buenos hábitos de las personas exitosas No basta con querer ser exitoso para lograrlo. Las personas exitosas tienen hábitos que los han llevado al lugar donde están.','tips consejo financieros'],
['Tips Consejos Financieros | Haga Cuentas','Los gastos que descuadran su presupuesto A todos nos ha ocurrido que salen gastos inesperados que nos descuadran el presupuesto; por ejemplo: Alguien cumple años y debemos llevarle un regalo. Se dañó el celular y hay arreglarlo o cambiarlo. La maleta se rompió y es necesario remplazarla. Tuvimos que comprar unos medicamentos. Gastos como estos hay muchos.','tips consejo financieros'],
['Tips Consejos Financieros | Haga Cuentas','Empiece ya mismo: no es necesario esperar a que sea lunes, el cumpleaños o el año nuevo… Inicie con la cantidad de dinero que pueda; algunas personas dicen que empezarán cuando completen cierta suma, con lo cual solo consiguen no ahorrar.','tips consejo financieros'],
['Tips Consejos Financieros | Haga Cuentas','Ahorre en sus servicios de telecomunicaciones La comunicación por teléfono móvil, fijo e internet se ha convertido en un gasto necesario; por ello es conveniente tomar medidas para ahorrar','tips consejo financieros'],
['Tips Consejos Financieros | Haga Cuentas','Cómo ahorrar en fechas especiales En las fechas especiales, como el día de la madre, la Navidad y el cumpleaños, demostramos nuestro afecto a través de regalos.','tips consejo financieros'],
['Tips Consejos Financieros | Haga Cuentas','Cómo ahorrar en los gastos de su mascota Los animales domésticos se han convertido en una parte importante de las familias y de muchas personas solas que comparten su hogar con una mascota.','tips consejo financieros'],
['Tips Consejos Financieros | Haga Cuentas','La importancia del ahorro y los seguros en la familia ¿Sabía que 7 de cada 10 familias no ahorran y muy pocas se aseguran? Es un alto riesgo que puede afectar la estabilidad económica del hogar.','tips consejo financieros'],
['Tips Consejos Financieros | Haga Cuentas','¿Sabe cómo funcionan los bolsillos de ahorro? Un Bolsillo de Ahorro es un servicio, asociado a una cuenta de ahorro, que le permite ahorrar de manera mensual, organizada y segura con una destinación específica.','tips consejo financieros'],
['Tips Consejos Financieros | Haga Cuentas','La cuenta de ahorros para Pensionados ¿Ha pensado en sus finanzas para la época de su retiro laboral? ¿Sabe qué productos financieros ofrecen para ese momento?','tips consejo financieros'],
['Tips Consejos Financieros | Haga Cuentas','4 recomendaciones para controlar pequeños gastos Puede parecer exagerado pero llevar el registro de todo lo que gasta diariamente es una forma efectiva de identificar esos pequeños gastos, la proporción que representan frente a sus ingresos y cómo impactan sus finanzas personales.','tips consejo financieros'],
['Tips Consejos Financieros | Haga Cuentas','Conozca las diferencias entre ahorrar e invertir Tomar la decisión entre ahorrar o invertir depende de su perfil de riesgo y la disponibilidad con la que va a requerir el dinero.','tips consejo financieros'],
['Tips Consejos Financieros | Haga Cuentas','La importancia de enseñarles a ahorrar a los niños El ahorro es uno de los primeros temas financieros que los niños deben aprender, pues les será clave para alcanzar muchas de sus metas.','tips consejo financieros'],
['Tips Consejos Financieros | Haga Cuentas','En octubre de 1924, un grupo de economistas y representantes de varios países se reunieron en Italia, en el Congreso Internacional del Ahorro, con el objetivode organizar y legislar las cajas de ahorro, y definieron octubre como el mes del ahorro.','tips consejo financieros'],
['Tips Consejos Financieros | Haga Cuentas','¿Alguna vez ha escuchado: “Cuando gane más empiezo a ahorrar”? Creer que para ahorrar se necesita ganar mucho dinero es uno de los mitos más comunes. Aquí le contamos algunos y cómo hacerles frente','tips consejo financieros'],
['Tips Consejos Financieros | Haga Cuentas','Tener pareja es una oportunidad para manejar mejor el dinero. Los regalos, las salidas y las visitas, cuestan; sin embargo, los novios y amigos también puedenser buenos ahorradores. Entonces, ¿cómo manejar las finanzas en pareja?','tips consejo financieros'],
['Tips Consejos Financieros | Haga Cuentas','Cómo funciona el crédito en las tarjetas de crédito Al usar su tarjeta de crédito está tomando dinero prestado de la entidad emisora, la cual paga al comercio la compra realizada y envía al cliente la cuenta por pagar, con un resumen de las compras, diferidas en las cuotas elegidas.','tips consejo financieros'],
['Tips Consejos Financieros | Haga Cuentas','No basta con querer ser exitoso para lograrlo. Las personas exitosas tienen hábitos que los han llevado al lugar donde están.','tips consejo financieros'],
['Tips Consejos Financieros | Haga Cuentas','La banca digital es para usted Cada vez es más común gestionar las finanzas desde el móvil; además de ahorrar costos, permite usar el tiempo más eficientemente.','tips consejo financieros'],
['Tips Consejos Financieros | Haga Cuentas','Seguridad en la banca virtual La forma de hacer transacciones bancarias ha cambiado en los últimos años; ahora es común realizar pagos y consultas por internet, ya sea desde el computador o el celular. ','tips consejo financieros'],
['Tips Consejos Financieros | Haga Cuentas','¿Qué es la disrupción digital? Mucho se ha hablado sobre la transformación digital pero, ¿ha escuchado el término disrupción digital? Hace referencia al cambio que enfrentan las personas debido a la nueva realidad en la forma de comunicarse, relacionarse y conectarse, pasando de lo físico a lo virtual.','tips consejo financieros'],
['Tips Consejos Financieros | Haga Cuentas','Más canales para realizar sus transacciones bancarias El talonario, la tarjeta débito, la oficina y los cajeros automáticos son formas o canales de atención utilizados por los clientes de los bancos desde hace años.','tips consejo financieros'],
['Tips Consejos Financieros | Haga Cuentas','Uso seguro de los canales digitales. Para mayor seguridad en el manejo del dinero en la banca digital, siga estas recomendaciones: Realice sus transacciones en los sitios web o apps oficiales de las entidades financieras.','tips consejo financieros'],
['Tips Consejos Financieros | Haga Cuentas','Domiciliación: el pago de sus servicios, siempre al día Es un servicio que ofrecen las entidades financieras para debitar mensualmente de cuentas de ahorro o corriente, o cargar a las tarjetas de crédito los pagos de servicios públicos y privados.','tips consejo financieros'],
['Tips Consejos Financieros | Haga Cuentas','Beneficios de la banca digital Ya no es necesario ir a las oficinas bancarias; gracias a los canales digitales, en muchas entidades financieras usted puede ahorrar tiempo y filas para abrir un producto o utilizar un servicio desde cualquier lugar, con un dispositivo que tenga acceso a internet.','tips consejo financieros'],
['Tips Consejos Financieros | Haga Cuentas','¿Cómo hacer pagos a través de PSE? PSE (Pagos Seguros en Línea) es una plataforma, vigilada por la Superintendencia Financiera, que permite realizar compras y pagos desde internet en más de 6.000 comercios registrados, utilizando los recursos de su cuenta de ahorros o corriente.','tips consejo financieros'],
['Tips Consejos Financieros | Haga Cuentas','Pague los servicios públicos sin salir de casa Ahórrese largas filas, pues ahora pagar los recibos de los servicios públicos desde internet es sencillo y cómodo.','tips consejo financieros'],
['Tips Consejos Financieros | Haga Cuentas','Facturas electrónicas: ayude al planeta y pague desde su casa Recibir las facturas electrónicas no solo le permite ser ambientalmente responsable, sino también pagar desde la comodidad de su casa. ','tips consejo financieros'],
['Tips Consejos Financieros | Haga Cuentas','El tiempo es oro. ¡No lo desperdicie pagando facturas! Ya no tendrá que hacer las largas filas y salir de casa para pagar facturas.','tips consejo financieros'],
['Tips Consejos Financieros | Haga Cuentas','Pagos y transferencias a través de dispositivos móviles Existen diferentes opciones para realizar transacciones seguras desde sus dispositivos móviles, como el celular.','tips consejo financieros'],
['Tips Consejos Financieros | Haga Cuentas','Mitos sobre la banca digital Los clientes de las entidades financieras pueden realizar sus trámites bancarios y pagos a través de dispositivos móviles, como el celular.','tips consejo financieros'],
['Tips Consejos Financieros | Haga Cuentas','Un código QR puede arreglarle el día Un código QR es una imagen que guarda en la web información codificada. Se utiliza, entre otros fines, para pagar productos y servicios, realizar transacciones y hacer transferencias a cuentas de ahorro y corriente.','tips consejo financieros'],
['Tips Consejos Financieros | Haga Cuentas','¿Conoce cómo funcionan las pólizas exequiales? Los seguros o pólizas exequiales cubren los gastos que conlleva un fallecimiento y evitan que en ese momento tenga que solicitar préstamos o recurrir a los ahorros, afectando así sus finanzas personales.','tips consejo financieros'],
['Tips Consejos Financieros | Haga Cuentas','Los seguros de educación ofrecen beneficios como: Acceder a las mejores instituciones del país, sin importar el valor de la matrícula. Garantizar el pago de la universidad por lo menos durante 10 semestres.','tips consejo financieros'],
['Tips Consejos Financieros | Haga Cuentas','¿Sabe cómo funciona el seguro de desempleo? Según estadísticas, en Colombia una persona se demora aproximadamente 6 meses en conseguir trabajo.','tips consejo financieros'],
['Tips Consejos Financieros | Haga Cuentas','Seguros no convencionales Los seguros más conocidos son los de vida, salud, vehículo y hogar.','tips consejo financieros'],
['Tips Consejos Financieros | Haga Cuentas','Prepárese para Declarar Renta en el 2019 Entre el 6 de agosto y el 17 de octubre serán los vencimientos para que las personas naturales presenten su Declaración de Renta correspondiente al año gravable 2018; por esto es importante prepararse desde ya.','tips consejo financieros'],
['Tips Consejos Financieros | Haga Cuentas','Cómo aprovechar los alimentos orgánicos y cuidar el bolsillo Los alimentos orgánicos, tanto las frutas y verduras como los preparados, son más saludables pero normalmente más costosos que los productos convencionales, pues requieren cuidados y desarrollos especiales.','tips consejo financieros'],
['Tips Consejos Financieros | Haga Cuentas','Ideas de menú navideño Nada mejor que atender a sus invitados con deliciosos pasabocas, cuidando asimismo su bolsillo','tips consejo financieros'],
['Tips Consejos Financieros | Haga Cuentas','4 propósitos financieros para este nuevo año A veces los propósitos de año nuevo no se cumplen por ser muy generales o muy complejos.','tips consejo financieros'],
['Tips Consejos Financieros | Haga Cuentas','¿Cómo manejar el apoyo económico que pueden requerir su familares? Hay momentos en que es necesario prestarle ayuda económica a un familiar, ya sea porque envejece, enferma o se queda sin empleo.','tips consejo financieros'],
['Tips Consejos Financieros | Haga Cuentas','Los errores más comunes a la hora de manejar las finanzas en pareja No compartir sus opiniones y creencias acerca de las finanzas con sinceridad o evitar hablar del tema por temor a diferencias y confrontaciones.','tips consejo financieros'],
['Tips Consejos Financieros | Haga Cuentas','¿Cómo construir patrimonio en pareja? El Patrimonio en la pareja va más allá de un tema legal y contable del matrimonio, pues representa progreso y calidad de vida para la familia y requiere de esfuerzo, compromiso y planeación permanente.','tips consejo financieros'],
['Tips Consejos Financieros | Haga Cuentas','El manejo del dinero ante la muerte de un ser querido Algunos aspectos de índole financiero que debe tener en cuenta en estos difíciles momentos para la familia son: Averigüe si el fallecido contaba con un seguro de vida o una póliza con servicios funerarios que pueda ser utilizada.','tips consejo financieros'],
['Tips Consejos Financieros | Haga Cuentas','¿Cómo administrar mejor el dinero en pareja? Un aspecto fundamental para el buen funcionamiento de una relación de pareja es la administración del dinero.','tips consejo financieros'],
['Tips Consejos Financieros | Haga Cuentas','Involucre a sus hijos en las finanzas No importa la etapa en que estén, siempre hay una buena oportunidad para que hable con sus hijos sobre finanzas y los introduzca en el tema','tips consejo financieros'],
['Tips Consejos Financieros | Haga Cuentas','Aproveche los beneficios del seguro de su vehículo Tener un vehículo les brinda calidad de vida a usted y a su familia.','tips consejo financieros'],
['Tips Consejos Financieros | Haga Cuentas','Beneficios de comprar vivienda Tener vivienda propia es una excelente forma de invertir; cada cuota pagada de su crédito hipotecario o leasing habitacional va directamente a su patrimonio y no es un gasto, como el arriendo. ','tips consejo financieros'],
['Tips Consejos Financieros | Haga Cuentas','¿Pensando en remodelar? Sea por gusto o por necesidad, desde el aspecto financiero es importante planear muy bien las remodelaciones o mejoras del hogar.','tips consejo financieros'],
['Tips Consejos Financieros | Haga Cuentas','Viaje feliz en su vehículo Viajar es algo que todos disfrutamos; nuestro país tiene paisajes extraordinarios, lugares acogedores y una gran variedad gastronómica.','tips consejo financieros'],
['Tips Consejos Financieros | Haga Cuentas','Su vivienda, lo más importante Tener vivienda propia tiene responsabilidades, y es importante estar pendiente de todos los aspectos para que no se desorganicen sus finanzas personales; por eso le recomendamos','tips consejo financieros'],
['Tips Consejos Financieros | Haga Cuentas','¿Cómo impactan los indicadores económicos sus finanzas personales? Los seguros más conocidos son los de vida, salud, vehículo y hogar.','tips consejo financieros'],
['Tips Consejos Financieros | Haga Cuentas','¿Qué tanto impacta el precio del dólar las finanzas personales de los colombianos? En poco más de dos años, la tasa de cambio pasó de alrededor de 2.000 pesos por dólar a 3.300 pesos.','tips consejo financieros']]
export default seoInfo;
